config/routes.rb
Rails.application.routes.draw do
  resources :writings
  resources :individuals
  resources :individualcategories
  get 'control_users/index'
  resources :articles
  resources :events
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/writing.rb
class Writing < ApplicationRecord
    has_many :individualwritings
    has_many :individuals, :through => :individualwritings, dependent: :destroy

    accepts_nested_attributes_for :individuals, reject_if: :all_blank, allow_destroy: true
end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  before_action :set_writing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  # GET /writings
  # GET /writings.json
  def index
    @writings = Writing.all.order("year DESC")
  end

  # GET /writings/1
  # GET /writings/1.json
  def show
  end

  # GET /writings/new
  def new
    @writing = Writing.new
  end

  # GET /writings/1/edit
  def edit
  end

  # POST /writings
  # POST /writings.json
  def create
    @writing = Writing.new(writing_params)

    respond_to do |format|
      if @writing.save
        format.html { redirect_to @writing, notice: 'Writing was successfully created.' }
        format.json { render :show, status: :created, location: @writing }
      else
        format.html { render :new }
        format.json { render json: @writing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /writings/1
  # PATCH/PUT /writings/1.json
  def update
    respond_to do |format|
      if @writing.update(writing_params)
        format.html { redirect_to @writing, notice: 'Writing was successfully updated.' }
        format.json { render :show, status: :ok, location: @writing }
      else
        format.html { render :edit }
        format.json { render json: @writing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /writings/1
  # DELETE /writings/1.json
  def destroy
    @writing.destroy
    respond_to do |format|
      format.html { redirect_to writings_url, notice: 'Writing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_writing
      @writing = Writing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def writing_params
      params.require(:writing).permit(:title, :link, :year, { :individual_ids => [] })
    end
end

app/helpers/writings_helper.rb
module WritingsHelper
end

app/views/writings/_admin_index.html.erb
<%- model_class = Writing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name("Individuals")%></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @writings.each do |writing| %>
      <tr>
        <td><%= link_to writing.id, writing_path(writing) %></td>
        <td><%= writing.title %></td>
        <td><%= (writing.link.blank?) ? 'empty' : 'filled' %></td>
        <td><%= writing.year %></td>
        <td><%= writing.individuals.count%></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      writing_path(writing), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_writing_path(writing), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      writing_path(writing),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_writing_path,
            :class => 'btn btn-primary' %>

app/views/writings/_form.html.erb
<%= form_for @writing, :html => { :class => "form-horizontal writing" } do |f| %>

  <% if @writing.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@writing.errors.count, "error") %> prohibited this writing from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @writing.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :link, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :link, :class => 'form-control' %>
    </div>
    <%=f.error_span(:link) %>
  </div>
  <div class="form-group">
    <%= f.label :year, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :year, :class => 'form-control' %>
    </div>
    <%=f.error_span(:year) %>
  </div>

  <div class="form-group">
    <%= f.label :individuals, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= collection_select(:writing, :individual_ids, Individual.all.order(:name), :id, :name, {}, { :multiple => true }) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                writings_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/writings/_normal_user.html.erb
<%- model_class = Writing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name("Individuals")%></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @writings.each do |writing| %>
      <tr>
        <td><%= link_to writing.id, writing_path(writing) %></td>
        <td><%= writing.title %></td>
        <td><%= (writing.link.blank?) ? 'empty' : 'filled' %></td>
        <td><%= writing.year %></td>
        <td><%= writing.individuals.count%></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      writing_path(writing), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_writing_path(writing), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      writing_path(writing),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_writing_path,
            :class => 'btn btn-primary' %>

app/views/writings/_not_logged.html.erb
<%- model_class = Writing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name("Individuals")%></th>
    </tr>
  </thead>
  <tbody>
    <% @writings.each do |writing| %>
      <tr>
        <td><%= link_to writing.id, writing_path(writing) %></td>
        <td><%= writing.title %></td>
        <td><%= (writing.link.blank?) ? 'empty' : 'filled' %></td>
        <td><%= writing.year %></td>
        <td><%= writing.individuals.count%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/writings/edit.html.erb
<%- model_class = Writing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/writings/index.html.erb
<% if user_signed_in? %>
  <% if policy(@writings).index? %>
    <%= render partial: "admin_index"%>
  <% else %>
    <%= render partial: "normal_user"%>
  <% end %>
<% else %>
  <%= render partial: "not_logged"%>
<% end %>

app/views/writings/new.html.erb
<%- model_class = Writing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/writings/show.html.erb
<%- model_class = Writing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @writing.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= @writing.link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= @writing.year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:individual) %>:</strong></dt>
  <dd><%= @writing.individuals.map(&:name).join(', ') %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              writings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_writing_path(@writing), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              writing_path(@writing),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>