config/routes.rb
Rails.application.routes.draw do
  resources :writings
  resources :individuals
  resources :individualcategories
  get 'control_users/index'
  resources :articles
  resources :events
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/individualcategory.rb
class Individualcategory < ApplicationRecord
    has_many :individuals, dependent: :destroy

    accepts_nested_attributes_for :individuals, reject_if: :all_blank, allow_destroy: true
end

app/controllers/individualcategories_controller.rb
class IndividualcategoriesController < ApplicationController
  before_action :set_individualcategory, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /individualcategories
  # GET /individualcategories.json
  def index
    @individualcategories = Individualcategory.all.order(:name)
  end

  # GET /individualcategories/1
  # GET /individualcategories/1.json
  def show
  end

  # GET /individualcategories/new
  def new
    @individualcategory = Individualcategory.new
    authorize Individualcategory
  end

  # GET /individualcategories/1/edit
  def edit
    authorize Individualcategory
  end

  # POST /individualcategories
  # POST /individualcategories.json
  def create
    @individualcategory = Individualcategory.new(individualcategory_params)

    respond_to do |format|
      if @individualcategory.save
        format.html { redirect_to @individualcategory, notice: 'Individualcategory was successfully created.' }
        format.json { render :show, status: :created, location: @individualcategory }
      else
        format.html { render :new }
        format.json { render json: @individualcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /individualcategories/1
  # PATCH/PUT /individualcategories/1.json
  def update
    respond_to do |format|
      if @individualcategory.update(individualcategory_params)
        format.html { redirect_to @individualcategory, notice: 'Individualcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @individualcategory }
      else
        format.html { render :edit }
        format.json { render json: @individualcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /individualcategories/1
  # DELETE /individualcategories/1.json
  def destroy
    @individualcategory.destroy
    respond_to do |format|
      format.html { redirect_to individualcategories_url, notice: 'Individualcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_individualcategory
      @individualcategory = Individualcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def individualcategory_params
      params.require(:individualcategory).permit(:name)
    end
end

app/helpers/individualcategories_helper.rb
module IndividualcategoriesHelper
end

app/views/individualcategories/_admin_index.html.erb
<%- model_class = Individualcategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize%></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @individualcategories.each do |individualcategory| %>
      <tr>
        <td><%= link_to individualcategory.id, individualcategory_path(individualcategory) %></td>
        <td><%= individualcategory.name %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      individualcategory_path(individualcategory), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_individualcategory_path(individualcategory), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      individualcategory_path(individualcategory),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_individualcategory_path,
            :class => 'btn btn-primary' %>

app/views/individualcategories/_form.html.erb
<%= form_for @individualcategory, :html => { :class => "form-horizontal individualcategory" } do |f| %>

  <% if @individualcategory.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@individualcategory.errors.count, "error") %> prohibited this individualcategory from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @individualcategory.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                individualcategories_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/individualcategories/_normal_user.html.erb
<%- model_class = Individualcategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
    </tr>
  </thead>
  <tbody>
    <% @individualcategories.each do |individualcategory| %>
      <tr>
        <td><%= link_to individualcategory.id, individualcategory_path(individualcategory) %></td>
        <td><%= individualcategory.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/individualcategories/edit.html.erb
<%- model_class = Individualcategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/individualcategories/index.html.erb
<% if user_signed_in? %>
  <% if policy(@individualcategories).index? %>
    <%= render partial: "admin_index"%>
  <% else %>
    <%= render partial: "normal_user"%>
  <% end %>
<% end %>

app/views/individualcategories/new.html.erb
<%- model_class = Individualcategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/individualcategories/show.html.erb
<%- model_class = Individualcategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @individualcategory.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              individualcategories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_individualcategory_path(@individualcategory), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              individualcategory_path(@individualcategory),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>